### ISSUE TITLE
[macOS] GL version incorrect, error cascade

### ISSUE THREAD

**Issue by GiveMeAnthony** [VDrift/vdrift#151] opened 2017-03-07 08:21 UTC
I have OpenGL 4.1 supported on my system, but running VDrift throws up a frozen screen. When I run it from Terminal, I get this cascade of errors. The first thing I noticed is that it detects OpenGL incorrectly. You need to set OpenGL forward compatibility to true and explicitly specify the core profile in order to use OpenGL 3.3 on macOS.

```
INFO: Multi-processor system detected.  Run with -multithreaded argument to enable multithreading (EXPERIMENTAL).
INFO: Starting VDrift: 2012-07-22a, Revision: 3-g7bbb48c, O/S: OS X
INFO: Home directory: /Users/Anthony
INFO: Settings file: /Users/Anthony/Library/Preferences/VDrift/VDrift.config
INFO: Data directory: /Applications/VDrift.app/Contents/Resources/data
INFO: Temporary directory: /Users/Anthony/Library/Preferences/VDrift/tmp
INFO: Log file: /Users/Anthony/Library/Preferences/VDrift/log.txt
INFO: Disabling antialiasing
INFO: Display change was successful: 800x600x32 24z fullscreen=0
INFO: GL Renderer: Intel(R) Iris(TM) Graphics 6100
INFO: GL Vendor: Intel Inc.
INFO: GL Version: 2.1 INTEL-10.22.29
INFO: Initialized GLEW 1.7.0
ERROR: Graphics card or driver does not support required GL_VERSION_3_3
ERROR: Initialization of GL3 failed; that's OK, falling back to GL 1 or 2
ERROR: You don't have an NVIDIA or ATI/AMD card.  This game may not run correctly or at all.
INFO: Video card information:
      Vendor: Intel Inc.
      Renderer: Intel(R) Iris(TM) Graphics 6100
      Version: 2.1 INTEL-10.22.29
      Maximum texture size: 16384
      Maximum varying floats: 60
      Using GLEW 1.7.0
INFO: Maximum color attachments: 8
INFO: Maximum draw buffers (1 required): 8
INFO: Texture units: 8 full, 16 partial
INFO: Loaded shader package simple
INFO: Loaded shader package simple, variant simple_premult
INFO: Loaded shader package simple, variant simple_gamma_premult
INFO: Loaded shader package simple, variant simple_gamma
INFO: Loaded shader package simple, variant simplecar
INFO: Loaded shader package tonemap
INFO: ----- Start Shader Link Log for /Applications/VDrift.app/Contents/Resources/data/shaders/gbufferfill/vertex.glsl and /Applications/VDrift.app/Contents/Resources/data/shaders/gbufferfill/fragment.glsl -----
INFO: WARNING: Output of vertex shader 'V' not read by fragment shader
      
INFO: ----- End Shader Link Log -----
INFO: Loaded shader package gbufferfill
INFO: ----- Start Shader Link Log for /Applications/VDrift.app/Contents/Resources/data/shaders/gbufferfill/vertex.glsl and /Applications/VDrift.app/Contents/Resources/data/shaders/gbufferfill/fragment.glsl -----
INFO: WARNING: Output of vertex shader 'V' not read by fragment shader
      
INFO: ----- End Shader Link Log -----
INFO: Loaded shader package gbufferfill, variant gbufferfillcar
INFO: ----- Start Shader Link Log for /Applications/VDrift.app/Contents/Resources/data/shaders/lightaccumulate/vertex.glsl and /Applications/VDrift.app/Contents/Resources/data/shaders/lightaccumulate/fragment.glsl -----
INFO: WARNING: Output of vertex shader 'tu0coord' not read by fragment shader
      
INFO: ----- End Shader Link Log -----
INFO: Loaded shader package lightaccumulate, variant lightaccumulate_initial
INFO: ----- Start Shader Link Log for /Applications/VDrift.app/Contents/Resources/data/shaders/lightaccumulate/vertex.glsl and /Applications/VDrift.app/Contents/Resources/data/shaders/lightaccumulate/fragment.glsl -----
INFO: WARNING: Output of vertex shader 'tu0coord' not read by fragment shader
      
INFO: ----- End Shader Link Log -----
INFO: Loaded shader package lightaccumulate, variant lightaccumulate_omni
INFO: Loaded shader package depthgen
INFO: Loaded shader package depthgen, variant depthgennoalpha
INFO: Loaded shader package distancefield
INFO: Loaded shader package deferredskybox
INFO: Loaded shader package deferredskyboxblend
INFO: Loaded shader package softparticle
INFO: Loaded shader package ppdepthadjust
INFO: Loaded shader package ppdepthadjust, variant ppcopy
INFO: Loaded shader package ppdepthadjust, variant ppcopy_gamma
INFO: Loaded shader package deferredshadows
INFO: ----- Start Shader Link Log for /Applications/VDrift.app/Contents/Resources/data/shaders/ssao/vertex.glsl and /Applications/VDrift.app/Contents/Resources/data/shaders/ssao/fragment.glsl -----
INFO: WARNING: Output of vertex shader 'eyespace_view_direction' not read by fragment shader
      
INFO: ----- End Shader Link Log -----
INFO: Loaded shader package ssao
INFO: Loaded shader package ssao_blur
INFO: Loaded shader package deferredaa
INFO: Successfully enabled shaders
INFO: Initialized render output: full_scene_depth (FBO)
INFO: Initialized render output: full_scene_color (FBO)
INFO: Initialized render output: full_scene_tonemapped (FBO)
INFO: Initialized render output: normal_xy (FBO)
INFO: Initialized render output: material_properties (FBO)
INFO: Initialized render output: diffuse_albedo (FBO)
INFO: Initialized render output: log_luminance (FBO)
INFO: Initialized render output: log_luminance_tiny (FBO)
Mar  7 00:06:45  VDrift[2530] <Error>: CGBitmapContextInfoCreate: CGColorSpace does't support output
Mar  7 00:06:45  VDrift[2530] <Error>: CGContextDrawImage: invalid context 0x0. If you want to see the backtrace, please set CG_CONTEXT_SHOW_BACKTRACE environmental variable.
Mar  7 00:06:45  VDrift[2530] <Error>: CGBitmapContextInfoCreate: CGColorSpace does't support output
Mar  7 00:06:45  VDrift[2530] <Error>: CGContextDrawImage: invalid context 0x0. If you want to see the backtrace, please set CG_CONTEXT_SHOW_BACKTRACE environmental variable.
INFO: Maximum anisotropy: 16
INFO: 0 joysticks found.
INFO: Loading car controls from: /Users/Anthony/Library/Preferences/VDrift/controls.config
INFO: Update status file /Users/Anthony/Library/Preferences/VDrift/updates.config will be created
INFO: Update status file /Users/Anthony/Library/Preferences/VDrift/updates.config will be created
INFO: Sound initialization information:
INFO: Obtained audio device:
      Frequency: 44100
      Format: 32784
      Bits per sample: 16
      Channels: 2
      Silence: 0
      Samples: 2048
      Size: 8192
      Sound initialization successful
Mar  7 00:06:45  VDrift[2530] <Error>: CGBitmapContextInfoCreate: CGColorSpace does't support output
Mar  7 00:06:45  VDrift[2530] <Error>: CGContextDrawImage: invalid context 0x0. If you want to see the backtrace, please set CG_CONTEXT_SHOW_BACKTRACE environmental variable.
Mar  7 00:06:45  VDrift[2530] <Error>: CGBitmapContextInfoCreate: CGColorSpace does't support output
Mar  7 00:06:45  VDrift[2530] <Error>: CGContextDrawImage: invalid context 0x0. If you want to see the backtrace, please set CG_CONTEXT_SHOW_BACKTRACE environmental variable.
Mar  7 00:06:45  VDrift[2530] <Error>: CGBitmapContextInfoCreate: CGColorSpace does't support output
Mar  7 00:06:45  VDrift[2530] <Error>: CGContextDrawImage: invalid context 0x0. If you want to see the backtrace, please set CG_CONTEXT_SHOW_BACKTRACE environmental variable.
Mar  7 00:06:45  VDrift[2530] <Error>: CGBitmapContextInfoCreate: CGColorSpace does't support output
Mar  7 00:06:45  VDrift[2530] <Error>: CGContextDrawImage: invalid context 0x0. If you want to see the backtrace, please set CG_CONTEXT_SHOW_BACKTRACE environmental variable.
INFO: Loaded fonts successfully
Mar  7 00:06:45  VDrift[2530] <Error>: CGBitmapContextInfoCreate: CGColorSpace does't support output
Mar  7 00:06:45  VDrift[2530] <Error>: CGContextDrawImage: invalid context 0x0. If you want to see the backtrace, please set CG_CONTEXT_SHOW_BACKTRACE environmental variable.
Mar  7 00:06:45  VDrift[2530] <Error>: CGBitmapContextInfoCreate: CGColorSpace does't support output
Mar  7 00:06:45  VDrift[2530] <Error>: CGContextDrawImage: invalid context 0x0. If you want to see the backtrace, please set CG_CONTEXT_SHOW_BACKTRACE environmental variable.
Mar  7 00:06:45  VDrift[2530] <Error>: CGBitmapContextInfoCreate: CGColorSpace does't support output
Mar  7 00:06:45  VDrift[2530] <Error>: CGContextDrawImage: invalid context 0x0. If you want to see the backtrace, please set CG_CONTEXT_SHOW_BACKTRACE environmental variable.
Mar  7 00:06:45  VDrift[2530] <Error>: CGBitmapContextInfoCreate: CGColorSpace does't support output
Mar  7 00:06:45  VDrift[2530] <Error>: CGContextDrawImage: invalid context 0x0. If you want to see the backtrace, please set CG_CONTEXT_SHOW_BACKTRACE environmental variable.
Mar  7 00:06:45  VDrift[2530] <Error>: CGBitmapContextInfoCreate: CGColorSpace does't support output
Mar  7 00:06:45  VDrift[2530] <Error>: CGContextDrawImage: invalid context 0x0. If you want to see the backtrace, please set CG_CONTEXT_SHOW_BACKTRACE environmental variable.
Mar  7 00:06:45  VDrift[2530] <Error>: CGBitmapContextInfoCreate: CGColorSpace does't support output
Mar  7 00:06:45  VDrift[2530] <Error>: CGContextDrawImage: invalid context 0x0. If you want to see the backtrace, please set CG_CONTEXT_SHOW_BACKTRACE environmental variable.
Mar  7 00:06:45  VDrift[2530] <Error>: CGBitmapContextInfoCreate: CGColorSpace does't support output
Mar  7 00:06:45  VDrift[2530] <Error>: CGContextDrawImage: invalid context 0x0. If you want to see the backtrace, please set CG_CONTEXT_SHOW_BACKTRACE environmental variable.
Mar  7 00:06:45  VDrift[2530] <Error>: CGBitmapContextInfoCreate: CGColorSpace does't support output
Mar  7 00:06:45  VDrift[2530] <Error>: CGContextDrawImage: invalid context 0x0. If you want to see the backtrace, please set CG_CONTEXT_SHOW_BACKTRACE environmental variable.
Mar  7 00:06:45  VDrift[2530] <Error>: CGBitmapContextInfoCreate: CGColorSpace does't support output
Mar  7 00:06:45  VDrift[2530] <Error>: CGContextDrawImage: invalid context 0x0. If you want to see the backtrace, please set CG_CONTEXT_SHOW_BACKTRACE environmental variable.
Mar  7 00:06:45  VDrift[2530] <Error>: CGBitmapContextInfoCreate: CGColorSpace does't support output
Mar  7 00:06:45  VDrift[2530] <Error>: CGContextDrawImage: invalid context 0x0. If you want to see the backtrace, please set CG_CONTEXT_SHOW_BACKTRACE environmental variable.
Mar  7 00:06:45  VDrift[2530] <Error>: CGBitmapContextInfoCreate: CGColorSpace does't support output
Mar  7 00:06:45  VDrift[2530] <Error>: CGContextDrawImage: invalid context 0x0. If you want to see the backtrace, please set CG_CONTEXT_SHOW_BACKTRACE environmental variable.
INFO: Loaded GUI successfully
Mar  7 00:06:46  VDrift[2530] <Error>: CGBitmapContextInfoCreate: CGColorSpace does't support output
Mar  7 00:06:46  VDrift[2530] <Error>: CGContextDrawImage: invalid context 0x0. If you want to see the backtrace, please set CG_CONTEXT_SHOW_BACKTRACE environmental variable.
Mar  7 00:06:46  VDrift[2530] <Error>: CGBitmapContextInfoCreate: CGColorSpace does't support output
Mar  7 00:06:46  VDrift[2530] <Error>: CGContextDrawImage: invalid context 0x0. If you want to see the backtrace, please set CG_CONTEXT_SHOW_BACKTRACE environmental variable.
Mar  7 00:06:46  VDrift[2530] <Error>: CGBitmapContextInfoCreate: CGColorSpace does't support output
Mar  7 00:06:46  VDrift[2530] <Error>: CGContextDrawImage: invalid context 0x0. If you want to see the backtrace, please set CG_CONTEXT_SHOW_BACKTRACE environmental variable.
Mar  7 00:06:46  VDrift[2530] <Error>: CGBitmapContextInfoCreate: CGColorSpace does't support output
Mar  7 00:06:46  VDrift[2530] <Error>: CGContextDrawImage: invalid context 0x0. If you want to see the backtrace, please set CG_CONTEXT_SHOW_BACKTRACE environmental variable.
Mar  7 00:06:46  VDrift[2530] <Error>: CGBitmapContextInfoCreate: CGColorSpace does't support output
Mar  7 00:06:46  VDrift[2530] <Error>: CGContextDrawImage: invalid context 0x0. If you want to see the backtrace, please set CG_CONTEXT_SHOW_BACKTRACE environmental variable.
Mar  7 00:06:46  VDrift[2530] <Error>: CGBitmapContextInfoCreate: CGColorSpace does't support output
Mar  7 00:06:46  VDrift[2530] <Error>: CGContextDrawImage: invalid context 0x0. If you want to see the backtrace, please set CG_CONTEXT_SHOW_BACKTRACE environmental variable.
INFO: Loading track from path: /Applications/VDrift.app/Contents/Resources/data/tracks/garage
INFO: Loaded surfaces file, 7 surfaces.
Mar  7 00:06:46  VDrift[2530] <Error>: CGBitmapContextInfoCreate: CGColorSpace does't support output
Mar  7 00:06:46  VDrift[2530] <Error>: CGContextDrawImage: invalid context 0x0. If you want to see the backtrace, please set CG_CONTEXT_SHOW_BACKTRACE environmental variable.
INFO: No lap sequence found. Lap timing will not be possible.
Mar  7 00:06:46  VDrift[2530] <Error>: CGBitmapContextInfoCreate: CGColorSpace does't support output
Mar  7 00:06:46  VDrift[2530] <Error>: CGContextDrawImage: invalid context 0x0. If you want to see the backtrace, please set CG_CONTEXT_SHOW_BACKTRACE environmental variable.
Mar  7 00:06:46  VDrift[2530] <Error>: CGBitmapContextInfoCreate: CGColorSpace does't support output
Mar  7 00:06:46  VDrift[2530] <Error>: CGContextDrawImage: invalid context 0x0. If you want to see the backtrace, please set CG_CONTEXT_SHOW_BACKTRACE environmental variable.
Mar  7 00:06:46  VDrift[2530] <Error>: CGBitmapContextInfoCreate: CGColorSpace does't support output
Mar  7 00:06:46  VDrift[2530] <Error>: CGContextDrawImage: invalid context 0x0. If you want to see the backtrace, please set CG_CONTEXT_SHOW_BACKTRACE environmental variable.
Mar  7 00:06:46  VDrift[2530] <Error>: CGBitmapContextInfoCreate: CGColorSpace does't support output
Mar  7 00:06:46  VDrift[2530] <Error>: CGContextDrawImage: invalid context 0x0. If you want to see the backtrace, please set CG_CONTEXT_SHOW_BACKTRACE environmental variable.
Mar  7 00:06:46  VDrift[2530] <Error>: CGBitmapContextInfoCreate: CGColorSpace does't support output
Mar  7 00:06:46  VDrift[2530] <Error>: CGContextDrawImage: invalid context 0x0. If you want to see the backtrace, please set CG_CONTEXT_SHOW_BACKTRACE environmental variable.
Mar  7 00:06:46  VDrift[2530] <Error>: CGBitmapContextInfoCreate: CGColorSpace does't support output
Mar  7 00:06:46  VDrift[2530] <Error>: CGContextDrawImage: invalid context 0x0. If you want to see the backtrace, please set CG_CONTEXT_SHOW_BACKTRACE environmental variable.
Mar  7 00:06:46  VDrift[2530] <Error>: CGBitmapContextInfoCreate: CGColorSpace does't support output
Mar  7 00:06:46  VDrift[2530] <Error>: CGContextDrawImage: invalid context 0x0. If you want to see the backtrace, please set CG_CONTEXT_SHOW_BACKTRACE environmental variable.
Mar  7 00:06:46  VDrift[2530] <Error>: CGBitmapContextInfoCreate: CGColorSpace does't support output
Mar  7 00:06:46  VDrift[2530] <Error>: CGContextDrawImage: invalid context 0x0. If you want to see the backtrace, please set CG_CONTEXT_SHOW_BACKTRACE environmental variable.
Mar  7 00:06:46  VDrift[2530] <Error>: CGBitmapContextInfoCreate: CGColorSpace does't support output
Mar  7 00:06:46  VDrift[2530] <Error>: CGContextDrawImage: invalid context 0x0. If you want to see the backtrace, please set CG_CONTEXT_SHOW_BACKTRACE environmental variable.
Mar  7 00:06:46  VDrift[2530] <Error>: CGBitmapContextInfoCreate: CGColorSpace does't support output
Mar  7 00:06:46  VDrift[2530] <Error>: CGContextDrawImage: invalid context 0x0. If you want to see the backtrace, please set CG_CONTEXT_SHOW_BACKTRACE environmental variable.
Mar  7 00:06:46  VDrift[2530] <Error>: CGBitmapContextInfoCreate: CGColorSpace does't support output
Mar  7 00:06:46  VDrift[2530] <Error>: CGContextDrawImage: invalid context 0x0. If you want to see the backtrace, please set CG_CONTEXT_SHOW_BACKTRACE environmental variable.
Mar  7 00:06:46  VDrift[2530] <Error>: CGBitmapContextInfoCreate: CGColorSpace does't support output
Mar  7 00:06:46  VDrift[2530] <Error>: CGContextDrawImage: invalid context 0x0. If you want to see the backtrace, please set CG_CONTEXT_SHOW_BACKTRACE environmental variable.
Mar  7 00:06:46  VDrift[2530] <Error>: CGBitmapContextInfoCreate: CGColorSpace does't support output
Mar  7 00:06:46  VDrift[2530] <Error>: CGContextDrawImage: invalid context 0x0. If you want to see the backtrace, please set CG_CONTEXT_SHOW_BACKTRACE environmental variable.
Mar  7 00:06:46  VDrift[2530] <Error>: CGBitmapContextInfoCreate: CGColorSpace does't support output
Mar  7 00:06:46  VDrift[2530] <Error>: CGContextDrawImage: invalid context 0x0. If you want to see the backtrace, please set CG_CONTEXT_SHOW_BACKTRACE environmental variable.
Mar  7 00:06:46  VDrift[2530] <Error>: CGBitmapContextInfoCreate: CGColorSpace does't support output
Mar  7 00:06:46  VDrift[2530] <Error>: CGContextDrawImage: invalid context 0x0. If you want to see the backtrace, please set CG_CONTEXT_SHOW_BACKTRACE environmental variable.
Mar  7 00:06:46  VDrift[2530] <Error>: CGBitmapContextInfoCreate: CGColorSpace does't support output
Mar  7 00:06:46  VDrift[2530] <Error>: CGContextDrawImage: invalid context 0x0. If you want to see the backtrace, please set CG_CONTEXT_SHOW_BACKTRACE environmental variable.
Mar  7 00:06:46  VDrift[2530] <Error>: CGBitmapContextInfoCreate: CGColorSpace does't support output
Mar  7 00:06:46  VDrift[2530] <Error>: CGContextDrawImage: invalid context 0x0. If you want to see the backtrace, please set CG_CONTEXT_SHOW_BACKTRACE environmental variable.
Mar  7 00:06:46  VDrift[2530] <Error>: CGBitmapContextInfoCreate: CGColorSpace does't support output
Mar  7 00:06:46  VDrift[2530] <Error>: CGContextDrawImage: invalid context 0x0. If you want to see the backtrace, please set CG_CONTEXT_SHOW_BACKTRACE environmental variable.
Mar  7 00:06:46  VDrift[2530] <Error>: CGBitmapContextInfoCreate: CGColorSpace does't support output
Mar  7 00:06:46  VDrift[2530] <Error>: CGContextDrawImage: invalid context 0x0. If you want to see the backtrace, please set CG_CONTEXT_SHOW_BACKTRACE environmental variable.
Mar  7 00:06:46  VDrift[2530] <Error>: CGBitmapContextInfoCreate: CGColorSpace does't support output
Mar  7 00:06:46  VDrift[2530] <Error>: CGContextDrawImage: invalid context 0x0. If you want to see the backtrace, please set CG_CONTEXT_SHOW_BACKTRACE environmental variable.
Mar  7 00:06:46  VDrift[2530] <Error>: CGBitmapContextInfoCreate: CGColorSpace does't support output
Mar  7 00:06:46  VDrift[2530] <Error>: CGContextDrawImage: invalid context 0x0. If you want to see the backtrace, please set CG_CONTEXT_SHOW_BACKTRACE environmental variable.
Mar  7 00:06:46  VDrift[2530] <Error>: CGBitmapContextInfoCreate: CGColorSpace does't support output
Mar  7 00:06:46  VDrift[2530] <Error>: CGContextDrawImage: invalid context 0x0. If you want to see the backtrace, please set CG_CONTEXT_SHOW_BACKTRACE environmental variable.
Mar  7 00:06:46  VDrift[2530] <Error>: CGBitmapContextInfoCreate: CGColorSpace does't support output
Mar  7 00:06:46  VDrift[2530] <Error>: CGContextDrawImage: invalid context 0x0. If you want to see the backtrace, please set CG_CONTEXT_SHOW_BACKTRACE environmental variable.
Mar  7 00:06:46  VDrift[2530] <Error>: CGBitmapContextInfoCreate: CGColorSpace does't support output
Mar  7 00:06:46  VDrift[2530] <Error>: CGContextDrawImage: invalid context 0x0. If you want to see the backtrace, please set CG_CONTEXT_SHOW_BACKTRACE environmental variable.
Mar  7 00:06:46  VDrift[2530] <Error>: CGBitmapContextInfoCreate: CGColorSpace does't support output
Mar  7 00:06:46  VDrift[2530] <Error>: CGContextDrawImage: invalid context 0x0. If you want to see the backtrace, please set CG_CONTEXT_SHOW_BACKTRACE environmental variable.
INFO: Car loading was successful: XS
Mar  7 00:06:46  VDrift[2530] <Error>: CGBitmapContextInfoCreate: CGColorSpace does't support output
Mar  7 00:06:46  VDrift[2530] <Error>: CGContextDrawImage: invalid context 0x0. If you want to see the backtrace, please set CG_CONTEXT_SHOW_BACKTRACE environmental variable.
```

**Comment by Timo6** [comment] 2017-03-07 11:42
Hi there, thanks for your message. The links on the homepage are out of date, so you are running an old version of VDrift. Try https://sourceforge.net/projects/vdrift/files/latest/download, or better yet build from source - we haven't done a release in a while!

**Comment by GiveMeAnthony** [comment] 2017-03-08 09:41
The 2014 version seems to work fine. Why isn't the homepage updated with this version?

```
Anthony Applications $ ./VDrift.app/Contents/MacOS/VDrift -multithreaded
INFO: Multithreading enabled: 4 processors
INFO: Starting VDrift: 2014-10-20, Revision: gd78b2c2, O/S: OS X
INFO: Home directory: /Users/Anthony
INFO: Settings file: /Users/Anthony/Library/Application Support/VDrift/VDrift.config
INFO: Data directory: /Applications/VDrift.app/Contents/Resources/data
INFO: Temporary directory: /Users/Anthony/Library/Application Support/VDrift/tmp
INFO: Log file: /Users/Anthony/Library/Application Support/VDrift/log.txt
INFO: Request OpenGL 3.3 Core Profile context.
INFO: Disabling antialiasing
INFO: Enabling vertical synchronization.
INFO: Video card information:
      GL Vendor: Intel Inc.
      GL Renderer: Intel(R) Iris(TM) Graphics 6100
      GL Version: 4.1 INTEL-10.22.29
      Texture units: 16
      Maximum texture size: 16384
INFO: Loading /Applications/VDrift.app/Contents/Resources/data/shaders/gl3/deferred.conf...
INFO: Loaded /Applications/VDrift.app/Contents/Resources/data/shaders/gl3/deferred.conf
INFO: GL3 initialization successful
INFO: 0 joysticks found.
INFO: Loading car controls from: /Users/Anthony/Library/Application Support/VDrift/controls.config
INFO: Update status file /Users/Anthony/Library/Application Support/VDrift/updates.config will be created
INFO: Update status file /Users/Anthony/Library/Application Support/VDrift/updates.config will be created
INFO: Sound initialization information:
INFO: Obtained audio device:
      Frequency: 44100
      Format: 32784
      Bits per sample: 16
      Channels: 2
      Silence: 0
      Samples: 2048
      Size: 8192
      Sound initialization successful
INFO: Loaded fonts successfully
INFO: Loaded GUI successfully
INFO: No force feedback devices found.
INFO: Loading track from path: /Applications/VDrift.app/Contents/Resources/data/skins/simple
INFO: Loaded surfaces file, 1 surfaces.
INFO: No lap sequence found. Lap timing will not be possible.
INFO: Car loading was successful: XS/XS
INFO: Loading track from path: /Applications/VDrift.app/Contents/Resources/data/tracks/ruudskogen
INFO: Loaded surfaces file, 6 surfaces.
INFO: Track timing sectors: 2
INFO: Car loading was successful: XS/XS
INFO: Car loading was successful: XS/XS
INFO: Got quit message from GUI. Shutting down...
INFO: Shutting down...
INFO: Exiting

```

**Comment by GiveMeAnthony** [comment] 2017-03-08 09:45
As for compiling from source, I seem to be missing the required frameworks but I couldn't find any information available on that. The following frameworks are highlighted red in XCode:

- Archive
- BulletCollision
- BulletDynamics
- BulletSoftBody
- GLEW
- cURL
- LinearMath
- Ogg
- SDL_image
- SDL
- Vorbis

**Comment by logzero** [comment] 2017-03-09 14:04
Nobody who still sticks around (me and timo) has the access rights to update the website.

I've been thinking about creating a differently named fork to work around this. On the other side I haven't had much time or motivation to work on vdrift recently.

**Comment by GiveMeAnthony** [comment] 2017-03-10 02:50
Ah, I see. If that's the case and we cannot contact those with access rights to the site, then it might be a good idea to put up a different site or fork and rename the project. Someone is surely paying for vdrift.net though, so it would be strange if they couldn't be contacted. But then again, after checking the whois information it shows that it was last updated 2013-12-17T17:42:36.00Z and that it will expire on 2017-07-09T16:08:26.00Z. So personally I lean toward throwing up a new site and I'd be willing to develop/design it, but I'd like to see what you think first since you're the main contributor.

Also, I've never been much of a social developer, as evidenced by my lack of GitHub contributions, but it seems that you could use macOS developers so I'd like to help in that regard where and when I can. Currently, this project isn't building on macOS because <libintl.h> from gettext is missing, so I'll start by working out the kinks in the build phase. Also, the preprocessor thought VERSION and REVISION were invalid octal numbers yesterday because of the `08`. The definitions.h file is in .gitignore so I can't add a commit to that.

**Comment by logzero** [comment] 2017-03-11 17:47
Github has a project (web)pages feature. A forum could be setup at forum.freegamedev.net as it is somewhat of a hub for foss game projects. It is all about time and motivation ;)

**Comment by logzero** [comment] 2017-06-13 14:17
Closing as "not a bug".

**Closed by logzero** 2017-06-13 14:17 UTC
